// <auto-generated />
using System;
using ExpenseTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ExpenseTrackerDbContext))]
    [Migration("20260401232443_InitialBookSchema")]
    partial class InitialBookSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.ExpenseEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("AmountOriginal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("AmountUsd")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstallmentIndex")
                        .HasColumnType("int");

                    b.Property<string>("InstallmentPlanId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("ManualFxRateToUsd")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("OccurredOn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("PaidWithCreditCard")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentExpectationConfirmedOn")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PaymentExpectationStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PaymentInstrumentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RecurringSeriesId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SubcategoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "CategoryId");

                    b.HasIndex("UserId", "InstallmentPlanId");

                    b.HasIndex("UserId", "OccurredOn");

                    b.HasIndex("UserId", "PaymentInstrumentId");

                    b.HasIndex("UserId", "RecurringSeriesId");

                    b.HasIndex("UserId", "SubcategoryId");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.ExpenseRecurringSeriesEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("AmountOriginal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("AmountUsd")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("AnchorOccurredOn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorizonMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("ManualFxRateToUsd")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<bool>("PaidWithCreditCard")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentInstrumentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RecurrenceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubcategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CategoryId");

                    b.HasIndex("UserId", "PaymentInstrumentId");

                    b.HasIndex("UserId", "SubcategoryId");

                    b.ToTable("expense_recurring_series", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.IncomeCategoryEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("income_categories", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.IncomeEntryEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("AmountOriginal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("AmountUsd")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectationConfirmedOn")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ExpectationStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IncomeCategoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IncomeSubcategoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("ManualFxRateToUsd")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("ReceivedOn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RecurringSeriesId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "IncomeCategoryId");

                    b.HasIndex("UserId", "IncomeSubcategoryId");

                    b.HasIndex("UserId", "ReceivedOn");

                    b.HasIndex("UserId", "RecurringSeriesId");

                    b.ToTable("income_entries", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.IncomeRecurringSeriesEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("AmountOriginal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("AmountUsd")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("AnchorReceivedOn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorizonMonths")
                        .HasColumnType("int");

                    b.Property<string>("IncomeCategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IncomeSubcategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("ManualFxRateToUsd")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("RecurrenceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IncomeCategoryId");

                    b.HasIndex("UserId", "IncomeSubcategoryId");

                    b.ToTable("income_recurring_series", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.IncomeSubcategoryEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemReserved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "CategoryId");

                    b.ToTable("income_subcategories", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.InstallmentPlanEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AnchorOccurredOn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntervalMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("ManualFxRateToUsd")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<int>("PaymentCount")
                        .HasColumnType("int");

                    b.Property<string>("PaymentInstrumentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("PerPaymentAmountOriginal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("PerPaymentAmountUsd")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("SubcategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CategoryId");

                    b.HasIndex("UserId", "PaymentInstrumentId");

                    b.HasIndex("UserId", "SubcategoryId");

                    b.ToTable("installment_plans", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.PaymentInstrumentEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("AnnualFeeAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("BankName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("BillingCycleDay")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("DisplaySuffix")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FeeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("MonthlyFeeAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("NominalAprPercent")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int?>("PaymentDueDay")
                        .HasColumnType("int");

                    b.Property<int?>("StatementClosingDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("payment_instruments", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.SubcategoryEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemReserved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "CategoryId");

                    b.ToTable("subcategories", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.UserBookMetadataEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BookRevision")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("user_book_metadata", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.UserPreferencesEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefaultCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LastPaymentInstrumentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Locale")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("UserId", "LastPaymentInstrumentId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.InstallmentPlanEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "InstallmentPlanId")
                        .OnDelete(DeleteBehavior.ClientSetNull);

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.PaymentInstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "PaymentInstrumentId")
                        .OnDelete(DeleteBehavior.ClientSetNull);

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.ExpenseRecurringSeriesEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "RecurringSeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.SubcategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.ExpenseRecurringSeriesEntity", b =>
                {
                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.PaymentInstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "PaymentInstrumentId")
                        .OnDelete(DeleteBehavior.ClientSetNull);

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.SubcategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.IncomeEntryEntity", b =>
                {
                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.IncomeCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "IncomeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.IncomeSubcategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "IncomeSubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.IncomeRecurringSeriesEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "RecurringSeriesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.IncomeRecurringSeriesEntity", b =>
                {
                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.IncomeCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "IncomeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.IncomeSubcategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "IncomeSubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.IncomeSubcategoryEntity", b =>
                {
                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.IncomeCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.InstallmentPlanEntity", b =>
                {
                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.PaymentInstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "PaymentInstrumentId")
                        .OnDelete(DeleteBehavior.ClientSetNull);

                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.SubcategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.SubcategoryEntity", b =>
                {
                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseTracker.Infrastructure.Data.Entities.UserPreferencesEntity", b =>
                {
                    b.HasOne("ExpenseTracker.Infrastructure.Data.Entities.PaymentInstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId", "LastPaymentInstrumentId")
                        .OnDelete(DeleteBehavior.ClientSetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
